version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-api-livros
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: api_livros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
